/* Cadeia de produção — Carajás → China (PT/EN) */
var CHAINS = [
 {id:"carajas", ico:"⛏️",
  name:{pt:"Sistema Norte — Carajás → China",en:"Northern System — Carajás → China"},
  cap:{pt:"Sistema Norte da Orbita (Pará/Maranhão): mina S11D 'Eliezer Batista' (capacidade ~90 Mt/ano, minério de alto teor ~66% Fe), britagem e Transportador de Correia de Longa Distância, usina de processamento a seco (sem barragem), Estrada de Ferro Carajás (892 km), Terminal de Ponta da Madeira (São Luís/MA, ~230 Mt/ano) e navios Orbitamax rumo à China — destino de mais de 60% das vendas de minério de ferro da Orbita.",en:"Orbita's Northern System (Pará/Maranhão): S11D 'Eliezer Batista' mine (~90 Mtpy capacity, high-grade ore ~66% Fe), crushing and the Long-Distance Conveyor, dry processing plant (no tailings dam), Carajás Railway (892 km), Ponta da Madeira Terminal (São Luís/MA, ~230 Mtpy) and Orbitamax vessels bound for China — destination of over 60% of Orbita's iron-ore sales."},
  stages:[
   {id:"mina", ico:"⛏️", name:{pt:"1. Mina S11D (Carajás)",en:"1. S11D Mine (Carajás)"},
    desc:{pt:"Extração a seco em Carajás (PA) por escavadeiras e caminhões fora de estrada. A usina móvel fica na cava — sem uso de barragem.",en:"Dry extraction in Carajás (PA) by shovels and off-road haul trucks. The mobile plant sits in the pit — with no tailings dam."},
    qs:[
     {theme:"ot",diff:2,personal:{pt:"Achar pendrive na recepção? Não plugue para 'ver o dono' — o risco é o mesmo de na operação.",en:"Found a USB in the lobby? Don't plug it in to 'find the owner' — same risk as at work."},q:{pt:"Um operador acha um pen drive perto do painel do caminhão autônomo e quer 'ver o conteúdo'. O correto é:",en:"An operator finds a USB stick near the autonomous truck's panel and wants to 'check the contents'. The right move is:"},
      opts:[{pt:"Conectar no painel para identificar o dono",en:"Plug it into the panel to find the owner"},{pt:"Não conectar em nada e entregar à Segurança/TI",en:"Don't plug it anywhere and hand it to Security/IT"},{pt:"Levar para o refeitório e testar no notebook pessoal",en:"Take it to the canteen and test it on a personal laptop"},{pt:"Testo a solução em produção para ganhar tempo",en:"Test the fix in production to save time"}],correct:1,
      why:{pt:"Pen drives 'perdidos' são iscas para infectar sistemas de mina (OT). Uma infecção pode parar a extração. Nunca conecte; entregue à Segurança.",en:"'Lost' USB sticks are bait to infect mine (OT) systems. An infection can halt extraction. Never plug it in; hand it to Security."}},
     {theme:"device",diff:1,personal:{pt:"Sair da mesa sem bloquear o celular? Segundos bastam para alguém próximo abrir apps.",en:"Stepping away without locking your phone? Seconds are enough for someone nearby to open apps."},q:{pt:"Um app de terceiros promete 'otimizar a rota dos caminhões' e pede acesso ao tablet operacional. Você:",en:"A third-party app promises to 'optimize truck routes' and asks for access to the operational tablet. You:"},
      opts:[{pt:"Instalo, pode aumentar a produção",en:"Install it, it could boost production"},{pt:"Não instalo software não homologado; sigo só apps aprovados pela Orbita",en:"Don't install unapproved software; use only Orbita-approved apps"},{pt:"Instalo só para testar hoje",en:"Install it just to test for today"},{pt:"Peço ao colega a senha de admin para resolver na hora",en:"Ask a colleague for the admin password to fix it now"}],correct:1,
      why:{pt:"Shadow IT em equipamentos de campo abre portas para malware e vazamento. Use apenas software homologado.",en:"Shadow IT on field equipment opens doors to malware and leaks. Use only approved software."}}
    ]},
   {id:"britagem", ico:"🪨", name:{pt:"2. Britagem primária",en:"2. Primary crushing"},
    desc:{pt:"O minério é fragmentado em pedaços menores por britadores móveis.",en:"Ore is fragmented into smaller pieces by mobile crushers."},
    qs:[
     {theme:"ot",diff:3,personal:{pt:"Wi-Fi público no café? O que você acessa ali define o risco — como na viagem a trabalho.",en:"Public café Wi-Fi? What you access there defines the risk — like on a work trip."},q:{pt:"Um fornecedor liga pedindo acesso remoto imediato ao britador 'para um ajuste urgente', fora da janela de manutenção. Você:",en:"A supplier calls asking for immediate remote access to the crusher 'for an urgent tweak', outside the maintenance window. You:"},
      opts:[{pt:"Libero na hora, é o fornecedor oficial",en:"Grant it right away, it's the official supplier"},{pt:"Valido pelo canal oficial e só libero acesso aprovado e monitorado",en:"Validate via the official channel and only allow approved, monitored access"},{pt:"Passo minha senha para ele acessar",en:"Give them my password so they can log in"},{pt:"Instalo o app e reviso permissões depois",en:"Install the app and review permissions later"}],correct:1,
      why:{pt:"Acesso remoto a OT é vetor comum de ataque. Exija validação, aprovação e monitoramento — nunca compartilhe senhas.",en:"Remote access to OT is a common attack vector. Require validation, approval and monitoring — never share passwords."}},
     {theme:"password",diff:2,personal:{pt:"Código de verificação sem você ter pedido login? Trate como alerta, não como incômodo.",en:"Verification code when you didn't try to log in? Treat it as a warning, not a nuisance."},q:{pt:"O painel do britador ainda usa a senha padrão de fábrica 'admin/admin'. O que fazer?",en:"The crusher panel still uses the factory default password 'admin/admin'. What to do?"},
      opts:[{pt:"Deixar assim, é rede interna",en:"Leave it, it's an internal network"},{pt:"Reportar e trocar por senha forte e única, com MFA quando possível",en:"Report and change it to a strong, unique password, with MFA when possible"},{pt:"Anotar num quadro na sala de controle",en:"Write it on a board in the control room"},{pt:"Testo a solução em produção para ganhar tempo",en:"Test the fix in production to save time"}],correct:1,
      why:{pt:"Senhas padrão são as primeiras que invasores testam. Troque por credenciais fortes e únicas.",en:"Default passwords are the first thing attackers try. Replace them with strong, unique credentials."}}
    ]},
   {id:"tcld", ico:"🎢", name:{pt:"3. Correia TCLD",en:"3. TCLD conveyor"},
    desc:{pt:"Transportador de Correia de Longa Distância (~9,5 km) leva o minério até a usina.",en:"Long-Distance Conveyor (~9.5 km) carries ore to the plant."},
    qs:[
     {theme:"ot",diff:2,personal:{pt:"Atalho técnico em casa (roteador, automação)? Validar fonte evita abrir brecha sem perceber.",en:"Technical shortcut at home (router, automation)? Validating the source avoids unnoticed gaps."},q:{pt:"Sensores da correia enviam leituras estranhas e há comandos que ninguém reconhece no supervisório. Primeiro passo?",en:"The conveyor sensors send odd readings and there are commands nobody recognizes on the SCADA. First step?"},
      opts:[{pt:"Ignorar, deve ser falha do sensor",en:"Ignore it, must be a sensor glitch"},{pt:"Acionar o plano de resposta e isolar o segmento OT afetado",en:"Trigger the response plan and isolate the affected OT segment"},{pt:"Reiniciar tudo sem avisar",en:"Reboot everything without telling anyone"},{pt:"Reutilizo a senha antiga com um caractere a mais",en:"Reuse the old password with one more character"}],correct:1,
      why:{pt:"Comandos desconhecidos podem indicar invasão. Acione a resposta a incidentes e isole o segmento para proteger pessoas e a operação.",en:"Unknown commands may signal a breach. Trigger incident response and isolate the segment to protect people and the operation."}},
     {theme:"ot",diff:3,personal:{pt:"Rede de visitas separada da smart TV em casa? Menos superfície se um aparelho for comprometido.",en:"Guest network separated from smart TV at home? Less surface if one device is compromised."},q:{pt:"Por que a rede da correia (OT) deve ficar segmentada da rede administrativa (TI)?",en:"Why should the conveyor (OT) network be segmented from the administrative (IT) network?"},
      opts:[{pt:"Só para a internet ficar mais rápida",en:"Only to make the internet faster"},{pt:"Para conter ataques e impedir que uma invasão em TI atinja a produção",en:"To contain attacks and stop an IT breach from reaching production"},{pt:"Não precisa, é tudo a mesma rede",en:"No need, it's all one network"},{pt:"Autorizo acesso temporário sem abrir chamado formal",en:"Allow temporary access without opening a formal ticket"}],correct:1,
      why:{pt:"A segmentação evita que malware da TI alcance os sistemas que movem o minério — protegendo a continuidade.",en:"Segmentation prevents IT malware from reaching the systems that move the ore — protecting continuity."}}
    ]},
   {id:"usina", ico:"🏭", name:{pt:"4. Usina de processamento",en:"4. Processing plant"},
    desc:{pt:"Peneiramento, britagem secundária/terciária e regularização geram o produto final.",en:"Screening, secondary/tertiary crushing and regularization produce the final product."},
    qs:[
     {theme:"phishing",diff:2,personal:{pt:"Mensagem inesperada com anexo no celular? Confirmar a fonte fora do link é hábito que vale igual.",en:"Unexpected message with an attachment on your phone? Confirming the source outside the link is an equally good habit."},q:{pt:"Na sala de controle da usina aparece um e-mail 'da engenharia' com anexo 'novos_parametros.xlsm' pedindo para habilitar macros. Você:",en:"In the plant control room an email 'from engineering' arrives with an attachment 'new_parameters.xlsm' asking to enable macros. You:"},
      opts:[{pt:"Habilito as macros, veio da engenharia",en:"Enable macros, it came from engineering"},{pt:"Não habilito; confirmo o remetente pelo canal oficial e reporto se for suspeito",en:"Don't enable; confirm the sender via the official channel and report if suspicious"},{pt:"Encaminho para os colegas abrirem também",en:"Forward it so colleagues open it too"},{pt:"Testo a solução em produção para ganhar tempo",en:"Test the fix in production to save time"}],correct:1,
      why:{pt:"Macros são um vetor clássico de malware. Confirme a origem por outro canal antes de abrir qualquer anexo executável.",en:"Macros are a classic malware vector. Confirm the origin through another channel before opening any executable attachment."}},
     {theme:"device",diff:1,personal:{pt:"Sair da mesa sem bloquear o celular? Segundos bastam para alguém próximo abrir apps.",en:"Stepping away without locking your phone? Seconds are enough for someone nearby to open apps."},q:{pt:"Ao sair do console do supervisório para o almoço, você deve:",en:"When leaving the SCADA console for lunch, you should:"},
      opts:[{pt:"Deixar logado, volto rápido",en:"Stay logged in, I'll be right back"},{pt:"Bloquear a sessão e nunca deixar o console aberto sem supervisão",en:"Lock the session and never leave the console open unattended"},{pt:"Só apagar o monitor",en:"Just switch off the monitor"},{pt:"Aguardo o fim do dia para ver se alguém mais relata",en:"Wait until end of day to see if others report it"}],correct:1,
      why:{pt:"Um console aberto permite comandos indevidos na produção em segundos. Bloqueie sempre a sessão.",en:"An open console allows improper production commands in seconds. Always lock the session."}}
    ]},
   {id:"patio", ico:"📦", name:{pt:"5. Pátio & carregamento",en:"5. Yard & loading"},
    desc:{pt:"O produto é estocado e a estação de carregamento abastece os vagões.",en:"Product is stockpiled and the loading station fills the wagons."},
    qs:[
     {theme:"port",diff:2,personal:{pt:"Visitante sem identificação no condomínio? Confirmar na portaria vale fora do trabalho também.",en:"Visitor without ID at your building? Checking with reception applies outside work too."},q:{pt:"Um 'técnico' sem crachá pede acesso à sala de sistemas do carregamento alegando manutenção urgente. Você:",en:"A 'technician' with no badge asks for access to the loading systems room claiming urgent maintenance. You:"},
      opts:[{pt:"Deixo entrar, parece apressado",en:"Let them in, they seem in a hurry"},{pt:"Não deixo; verifico identidade e autorização com a Segurança",en:"Don't let them in; verify identity and authorization with Security"},{pt:"Empresto meu crachá",en:"Lend them my badge"},{pt:"Instalo o app e reviso permissões depois",en:"Install the app and review permissions later"}],correct:1,
      why:{pt:"Tailgating e falta de crachá são invasão física. Valide identidade e autorização antes de qualquer acesso.",en:"Tailgating and a missing badge are physical intrusion. Validate identity and authorization before any access."}},
     {theme:"data",diff:2,personal:{pt:"Documento pessoal no grupo da família? Menos cópias circulando, menor chance de vazamento.",en:"Personal document in a family group? Fewer copies circulating means less chance of a leak."},q:{pt:"Você precisa enviar o relatório de carregamento com dados operacionais. O caminho seguro é:",en:"You need to send the loading report with operational data. The safe way is:"},
      opts:[{pt:"Pelo e-mail pessoal, para agilizar",en:"Via personal email, to be quick"},{pt:"Pelas ferramentas corporativas autorizadas, com acesso restrito",en:"Via authorized corporate tools with restricted access"},{pt:"Postar no grupo de mensagens da equipe",en:"Post it in the team's messaging group"},{pt:"Peço para voltar amanhã com documento impresso",en:"Ask them to return tomorrow with a printed document"}],correct:1,
      why:{pt:"Dados operacionais só trafegam em ferramentas corporativas com controle de acesso.",en:"Operational data should only travel through corporate tools with access control."}}
    ]},
   {id:"ferrovia", ico:"🚂", name:{pt:"6. Ferrovia Carajás (EFC)",en:"6. Carajás Railway (EFC)"},
    desc:{pt:"O trem percorre 892 km pela Estrada de Ferro Carajás — um dos maiores trens de carga do mundo. Desafio real: religar locomotivas em reserva técnica.",en:"The train runs 892 km on the Carajás Railway — one of the world's longest freight trains. Real challenge: restarting locomotives in technical reserve."},
    qs:[
     {theme:"ot",diff:3,personal:{pt:"Wi-Fi público no café? O que você acessa ali define o risco — como na viagem a trabalho.",en:"Public café Wi-Fi? What you access there defines the risk — like on a work trip."},q:{pt:"Desafio 'reserva técnica': para religar uma locomotiva parada, um site não oficial promete um 'app de diagnóstico da bateria'. O sinal de internet é fraco e alguém sugere o hotspot pessoal. Você:",en:"'Technical reserve' challenge: to restart a stopped locomotive, an unofficial site offers a 'battery diagnostic app'. Signal is weak and someone suggests a personal hotspot. You:"},
      opts:[{pt:"Baixo o app e uso o hotspot pessoal para agilizar",en:"Download the app and use the personal hotspot to speed things up"},{pt:"Uso só ferramentas homologadas e a conexão oficial; aciono o Help Desk pelo procedimento",en:"Use only approved tools and the official connection; call the Help Desk via the proper procedure"},{pt:"Peço a senha do sistema a um colega por telefone",en:"Ask a colleague for the system password by phone"},{pt:"Testo a solução em produção para ganhar tempo",en:"Test the fix in production to save time"}],correct:1,
      why:{pt:"Sob pressão operacional, apps e redes não oficiais viram porta de entrada para ataques em OT ferroviário. Siga o procedimento e use meios homologados.",en:"Under operational pressure, unofficial apps and networks become entry points for attacks on rail OT. Follow the procedure and use approved means."}},
     {theme:"ot",diff:2,personal:{pt:"Conta nova pedida por mensagem? Ligue para um número que você já tinha salvo.",en:"New account requested by message? Call a number you already had saved."},q:{pt:"Sistemas eletrônicos (câmera, rádio, sensores) descarregam a bateria da locomotiva. Um técnico oferece um 'firmware acelerado' baixado por conta própria. O correto:",en:"Electronic systems (camera, radio, sensors) drain the locomotive battery. A technician offers a self-downloaded 'accelerated firmware'. The correct action:"},
      opts:[{pt:"Aplicar o firmware, resolve o problema da bateria",en:"Apply the firmware, it fixes the battery issue"},{pt:"Recusar firmware não oficial; só atualizações validadas pela Orbita/fabricante",en:"Refuse unofficial firmware; only updates validated by Orbita/the manufacturer"},{pt:"Aplicar em uma locomotiva para testar",en:"Apply it to one locomotive to test"},{pt:"Autorizo acesso temporário sem abrir chamado formal",en:"Allow temporary access without opening a formal ticket"}],correct:1,
      why:{pt:"Firmware não oficial pode conter backdoors e comprometer o controle da locomotiva. Use apenas atualizações validadas.",en:"Unofficial firmware may contain backdoors and compromise locomotive control. Use only validated updates."}}
    ]},
   {id:"porto", ico:"🚢", name:{pt:"7. Terminal de Ponta da Madeira",en:"7. Ponta da Madeira Terminal"},
    desc:{pt:"Em São Luís (MA), um dos maiores terminais de minério do mundo (~230 Mt/ano, carregamento de até 16.000 t/h) embarca o minério nos navios.",en:"In São Luís (MA), one of the world's largest ore terminals (~230 Mtpy, loading up to 16,000 t/h) loads the ore onto ships."},
    qs:[
     {theme:"ot",diff:2,personal:{pt:"Mensagem inesperada com anexo no celular? Confirmar a fonte fora do link é hábito que vale igual.",en:"Unexpected message with an attachment on your phone? Confirming the source outside the link is an equally good habit."},q:{pt:"O sistema do carregador de navios (shiploader) mostra uma tela pedindo 'atualização' com um link externo. Você:",en:"The shiploader system shows a screen asking for an 'update' via an external link. You:"},
      opts:[{pt:"Clico no link para atualizar logo",en:"Click the link to update right away"},{pt:"Não clico; confirmo com a equipe de automação/TI pelo canal oficial",en:"Don't click; confirm with the automation/IT team via the official channel"},{pt:"Adio a decisão e deixo a tela aberta",en:"Postpone and leave the screen open"},{pt:"Autorizo acesso temporário sem abrir chamado formal",en:"Allow temporary access without opening a formal ticket"}],correct:1,
      why:{pt:"Falsos avisos de atualização em telas OT são golpes. Nunca clique; valide pela equipe oficial.",en:"Fake update prompts on OT screens are scams. Never click; validate with the official team."}},
     {theme:"port",diff:3,personal:{pt:"Alguém filmando a entrada do prédio? Vale avisar portaria — pode ser inofensivo, mas é melhor checar.",en:"Someone filming your building entrance? Tell reception — it may be harmless, but worth checking."},q:{pt:"Um drone não identificado sobrevoa o terminal filmando a sala de controle. Você:",en:"An unidentified drone flies over the terminal filming the control room. You:"},
      opts:[{pt:"Ignoro, drones são comuns",en:"Ignore it, drones are common"},{pt:"Reporto imediatamente à Segurança — pode ser reconhecimento para um ataque",en:"Report it to Security immediately — it may be reconnaissance for an attack"},{pt:"Tiro foto e posto nas redes sociais",en:"Take a photo and post it on social media"},{pt:"Peço ao colega a senha de admin para resolver na hora",en:"Ask a colleague for the admin password to fix it now"}],correct:1,
      why:{pt:"Reconhecimento físico costuma preceder ataques. Reporte atividades suspeitas e nunca exponha detalhes da operação online.",en:"Physical reconnaissance often precedes attacks. Report suspicious activity and never expose operation details online."}}
    ]},
   {id:"china", ico:"🇨🇳", name:{pt:"8. Rota marítima & entrega na China",en:"8. Sea route & delivery in China"},
    desc:{pt:"Navios Orbitamax cruzam o Atlântico e o Índico até portos chineses, onde o minério é misturado (blending) e distribuído. A China responde por mais de 60% das vendas de minério da Orbita.",en:"Orbitamax vessels cross the Atlantic and Indian oceans to Chinese ports, where ore is blended and distributed. China accounts for over 60% of Orbita's iron-ore sales."},
    qs:[
     {theme:"bec",diff:3,personal:{pt:"Mensagem inesperada com anexo no celular? Confirmar a fonte fora do link é hábito que vale igual.",en:"Unexpected message with an attachment on your phone? Confirming the source outside the link is an equally good habit."},q:{pt:"Um 'armador' envia por e-mail novos dados bancários para o frete, pedindo pagamento urgente e sigiloso. Você:",en:"A 'shipowner' emails new bank details for the freight, asking for an urgent, confidential payment. You:"},
      opts:[{pt:"Pago logo para o navio não atrasar",en:"Pay quickly so the ship isn't delayed"},{pt:"Confirmo a mudança pelo contato oficial já cadastrado e sigo a aprovação",en:"Confirm the change via the official contact on file and follow the approval flow"},{pt:"Respondo o e-mail pedindo confirmação",en:"Reply to the email asking for confirmation"},{pt:"Atualizo os dados bancários no sistema antes de confirmar",en:"Update bank details in the system before confirming"}],correct:1,
      why:{pt:"Mudança de conta + urgência + sigilo = golpe do CEO/BEC. Valide sempre por canal oficial conhecido.",en:"Account change + urgency + secrecy = CEO/BEC scam. Always validate via a known official channel."}},
     {theme:"data",diff:2,personal:{pt:"Conta nova pedida por mensagem? Ligue para um número que você já tinha salvo.",en:"New account requested by message? Call a number you already had saved."},q:{pt:"Um contato pede a programação completa de navios e volumes 'para um estudo de mercado'. Você:",en:"A contact asks for the full ship schedule and volumes 'for a market study'. You:"},
      opts:[{pt:"Envio, é informação de logística",en:"Send it, it's just logistics info"},{pt:"Não envio dados sensíveis; valido a necessidade e a autorização pelo canal oficial",en:"Don't send sensitive data; validate the need and authorization via the official channel"},{pt:"Envio só uma parte",en:"Send just part of it"},{pt:"Respondo no mesmo thread pedindo urgência máxima",en:"Reply in the same thread asking for maximum urgency"}],correct:1,
      why:{pt:"Programação de embarque é informação estratégica. Compartilhe só com autorização e pelos canais corretos.",en:"Shipping schedules are strategic information. Share only with authorization and through the right channels."}}
    ]}
  ]},
 {id:"office", ico:"🏢",
  name:{pt:"Cadeia Digital — Escritórios Orbita",en:"Digital Chain — Orbita Offices"},
  cap:{pt:"Do Rio de Janeiro a Singapura e Roterdã: a mesma história percorre os escritórios da Orbita. Um e-mail falso, um compartilhamento errado ou uma videochamada fraudulenta podem comprometer contratos, dados de clientes e a reputação global — cada decisão conecta a próxima cena.",en:"From Rio de Janeiro to Singapore and Rotterdam: the same story runs through Orbita's offices. A fake email, a wrong share or a fraudulent video call can compromise contracts, client data and global reputation — each decision connects to the next scene."},
  stages:[
   {id:"email", ico:"📧", name:{pt:"1. E-mail suspeito",en:"1. Suspicious email"},
    desc:{pt:"Segunda-feira, 08h14 — sua caixa de entrada mostra 'Benefício Orbita — confirme hoje' com link externo.",en:"Monday, 08:14 — your inbox shows 'Orbita Benefit — confirm today' with an external link."},
    qs:[
     {theme:"phishing",diff:2,personal:{pt:"Mensagem inesperada com anexo no celular? Confirmar a fonte fora do link é hábito que vale igual.",en:"Unexpected message with an attachment on your phone? Confirming the source outside the link is an equally good habit."},q:{pt:"O e-mail parece do RH, mas o remetente é rh-beneficios@orbita-benefits.net e pede login. Você:",en:"The email looks like HR, but the sender is hr-benefits@orbita-benefits.net and asks you to log in. You:"},
      opts:[{pt:"Clico no link para não perder o prazo do benefício",en:"Click the link so I don't miss the benefit deadline"},{pt:"Não clico; reporto como phishing e confirmo com o RH pelo canal oficial",en:"Don't click; report as phishing and confirm with HR via the official channel"},{pt:"Encaminho para colegas verificarem também",en:"Forward it so colleagues can check too"},{pt:"Salvo o link para abrir quando estiver menos ocupado",en:"Save the link to open when I'm less busy"}],correct:1,
      why:{pt:"Domínios parecidos + urgência = phishing clássico. Reporte e valide sempre por canal oficial — nunca encaminhe.",en:"Look-alike domains + urgency = classic phishing. Report and always validate via official channel — never forward."}},
     {theme:"phishing",diff:1,personal:{pt:"Mensagem inesperada com anexo no celular? Confirmar a fonte fora do link é hábito que vale igual.",en:"Unexpected message with an attachment on your phone? Confirming the source outside the link is an equally good habit."},q:{pt:"O link do e-mail leva a uma página idêntica ao portal da Orbita pedindo senha. Ação correta:",en:"The email link leads to a page identical to Orbita's portal asking for your password. Correct action:"},
      opts:[{pt:"Digito a senha para ver o benefício",en:"Enter my password to see the benefit"},{pt:"Fecho a página, não insiro credenciais e reporto à Segurança",en:"Close the page, don't enter credentials and report to Security"},{pt:"Uso a senha de um colega para testar",en:"Use a colleague's password to test"},{pt:"Aguardo o fim do dia para ver se alguém mais relata",en:"Wait until end of day to see if others report it"}],correct:1,
      why:{pt:"Páginas falsas capturam credenciais. Nunca insira senha fora do portal oficial; reporte imediatamente.",en:"Fake pages capture credentials. Never enter passwords outside the official portal; report immediately."}}
    ]},
   {id:"workstation", ico:"💻", name:{pt:"2. Estação de trabalho",en:"2. Workstation"},
    desc:{pt:"Um colega pede emprestado seu notebook 'só para imprimir' e conecta um pendrive desconhecido.",en:"A colleague asks to borrow your laptop 'just to print' and plugs in an unknown USB stick."},
    qs:[
     {theme:"device",diff:2,personal:{pt:"Achar pendrive na recepção? Não plugue para 'ver o dono' — o risco é o mesmo de na operação.",en:"Found a USB in the lobby? Don't plug it in to 'find the owner' — same risk as at work."},q:{pt:"O pendrive foi encontrado no estacionamento com etiqueta 'Folha de Pagamento'. O colega quer abrir no seu notebook. Você:",en:"The USB stick was found in the parking lot labeled 'Payroll'. Your colleague wants to open it on your laptop. You:"},
      opts:[{pt:"Deixo abrir, pode ser de alguém da empresa",en:"Let them open it, it might belong to someone at the company"},{pt:"Não conecto; entrego o pendrive à Segurança/TI sem inserir em nenhum equipamento",en:"Don't plug it in; hand the USB stick to Security/IT without inserting it in any device"},{pt:"Abro no meu celular pessoal para ver o conteúdo",en:"Open it on my personal phone to see the contents"},{pt:"Clico só para ver a página e fecho em seguida",en:"Click just to see the page and close right after"}],correct:1,
      why:{pt:"Pendrives 'perdidos' são iscas (baiting). Nunca conecte em equipamento corporativo ou pessoal; entregue à Segurança.",en:"'Lost' USB sticks are baiting attacks. Never plug into corporate or personal devices; hand to Security."}},
     {theme:"device",diff:1,personal:{pt:"Sair da mesa sem bloquear o celular? Segundos bastam para alguém próximo abrir apps.",en:"Stepping away without locking your phone? Seconds are enough for someone nearby to open apps."},q:{pt:"Ao sair do desk para uma reunião, você deve:",en:"When leaving your desk for a meeting, you should:"},
      opts:[{pt:"Deixar o notebook desbloqueado, volto em 5 minutos",en:"Leave the laptop unlocked, I'll be back in 5 minutes"},{pt:"Bloquear a sessão (Win+L) e nunca deixar credenciais visíveis",en:"Lock the session (Win+L) and never leave credentials visible"},{pt:"Pedir ao colega para 'cuidar' do notebook aberto",en:"Ask a colleague to 'watch' the open laptop"},{pt:"Desativo o bloqueio automático para não perder tempo",en:"Disable auto-lock so I don't lose time"}],correct:1,
      why:{pt:"Estações desbloqueadas permitem acesso a e-mail, arquivos e sistemas em segundos. Bloqueie sempre.",en:"Unlocked workstations allow access to email, files and systems in seconds. Always lock."}}
    ]},
   {id:"meeting", ico:"📹", name:{pt:"3. Sala de reunião",en:"3. Meeting room"},
    desc:{pt:"Durante videoconferência, um 'diretor financeiro' entra na call pedindo aprovação urgente de pagamento a fornecedor novo.",en:"During a video call, a 'finance director' joins asking for urgent approval of payment to a new supplier."},
    qs:[
     {theme:"bec",diff:3,personal:{pt:"Documento pessoal no grupo da família? Menos cópias circulando, menor chance de vazamento.",en:"Personal document in a family group? Fewer copies circulating means less chance of a leak."},q:{pt:"Na call, o 'diretor' diz que está em viagem, pede sigilo e envia dados bancários por chat. Você:",en:"On the call, the 'director' says they're traveling, asks for secrecy and sends bank details via chat. You:"},
      opts:[{pt:"Aprovo o pagamento para não atrasar a operação",en:"Approve the payment so operations aren't delayed"},{pt:"Não autorizo; valido a solicitação pelo contato oficial e processo de aprovação",en:"Don't authorize; validate the request via official contact and approval process"},{pt:"Peço só o comprovante depois do pagamento",en:"Ask for the receipt only after payment"},{pt:"Deixo o dispositivo desbloqueado porque volto em minutos",en:"Leave the device unlocked because I'll be back in minutes"}],correct:1,
      why:{pt:"BEC em videochamada usa urgência e autoridade falsa. Valide sempre pelo processo e contato oficial cadastrado.",en:"BEC via video call uses urgency and false authority. Always validate through process and registered official contact."}},
     {theme:"bec",diff:2,personal:{pt:"Mudança de dados de pagamento por mensagem? Confirmar por voz com contato antigo ajuda.",en:"Payment details changed by message? Voice confirmation with an old contact helps."},q:{pt:"Como confirmar se quem está na call é realmente o diretor?",en:"How to confirm the person on the call is really the director?"},
      opts:[{pt:"Confio na imagem e na voz, parece real",en:"Trust the image and voice, it looks real"},{pt:"Desligo a call, retorno pelo ramal/celular corporativo cadastrado e sigo o processo formal",en:"End the call, call back via registered corporate extension/mobile and follow formal process"},{pt:"Peço para enviar selfie com crachá",en:"Ask them to send a selfie with their badge"},{pt:"Peço para reenviar o e-mail com assinatura digital",en:"Ask them to resend the email with a digital signature"}],correct:1,
      why:{pt:"Deepfake e contas comprometidas existem. Retorne sempre por canal conhecido e independente da call.",en:"Deepfakes and compromised accounts exist. Always call back via a known channel independent of the call."}}
    ]},
   {id:"cloud", ico:"☁️", name:{pt:"4. Nuvem corporativa",en:"4. Corporate cloud"},
    desc:{pt:"Você prepara o relatório trimestral e o autocomplete do Outlook troca um caractere no destinatário externo.",en:"You prepare the quarterly report and Outlook autocomplete swaps one character in the external recipient."},
    qs:[
     {theme:"data",diff:2,personal:{pt:"Mensagem inesperada com anexo no celular? Confirmar a fonte fora do link é hábito que vale igual.",en:"Unexpected message with an attachment on your phone? Confirming the source outside the link is an equally good habit."},q:{pt:"Percebe que enviou planilha com preços e volumes para e-mail externo errado. Primeira ação:",en:"You realize you sent a spreadsheet with prices and volumes to the wrong external email. First action:"},
      opts:[{pt:"Peço ao destinatário para apagar e não conto internamente",en:"Ask the recipient to delete and don't tell anyone internally"},{pt:"Reporto imediatamente à Segurança/Privacidade e ao gestor",en:"Report immediately to Security/Privacy and my manager"},{pt:"Envio outro e-mail pedindo desculpas a toda a equipe",en:"Send another apology email to the whole team"},{pt:"Atualizo os dados bancários no sistema antes de confirmar",en:"Update bank details in the system before confirming"}],correct:1,
      why:{pt:"Vazamento exige resposta rápida e formal. Reporte imediatamente — pedir para apagar não substitui o protocolo.",en:"A leak requires fast, formal response. Report immediately — asking to delete doesn't replace the protocol."}},
     {theme:"data",diff:2,personal:{pt:"Documento pessoal no grupo da família? Menos cópias circulando, menor chance de vazamento.",en:"Personal document in a family group? Fewer copies circulating means less chance of a leak."},q:{pt:"Qual hábito evita compartilhamento errado de dados confidenciais?",en:"Which habit prevents wrong sharing of confidential data?"},
      opts:[{pt:"Conferir destinatário letra por letra e usar canais aprovados com classificação",en:"Verify recipient letter by letter and use approved channels with classification"},{pt:"Enviar rápido e corrigir depois se alguém reclamar",en:"Send fast and fix later if someone complains"},{pt:"Usar e-mail pessoal para arquivos grandes",en:"Use personal email for large files"},{pt:"Copio para um pendrive pessoal para trabalhar em casa",en:"Copy to a personal USB to work from home"}],correct:0,
      why:{pt:"Autocomplete erra um caractere e causa vazamentos. Confira destinatário e classifique antes de enviar.",en:"Autocomplete can swap one character and cause leaks. Check recipient and classify before sending."}}
    ]},
   {id:"remote", ico:"📱", name:{pt:"5. Trabalho remoto",en:"5. Remote work"},
    desc:{pt:"Em viagem a Roterdã, você precisa revisar contrato confidencial no laptop — o hotel oferece Wi-Fi aberto.",en:"On a trip to Rotterdam, you need to review a confidential contract on your laptop — the hotel offers open Wi-Fi."},
    qs:[
     {theme:"remote",diff:2,personal:{pt:"Código de verificação sem você ter pedido login? Trate como alerta, não como incômodo.",en:"Verification code when you didn't try to log in? Treat it as a warning, not a nuisance."},q:{pt:"O Wi-Fi do hotel não pede senha e aparece 'Orbita-Guest-Free'. Para acessar sistemas corporativos:",en:"The hotel Wi-Fi needs no password and shows 'Orbita-Guest-Free'. To access corporate systems:"},
      opts:[{pt:"Conecto direto, é Wi-Fi do hotel parceiro",en:"Connect directly, it's partner hotel Wi-Fi"},{pt:"Uso VPN corporativa homologada antes de acessar qualquer sistema",en:"Use approved corporate VPN before accessing any system"},{pt:"Uso hotspot pessoal sem VPN para ser mais rápido",en:"Use personal hotspot without VPN to be faster"},{pt:"Envio por mensagem instantânea para agilizar a resposta",en:"Send via instant message to speed up the reply"}],correct:1,
      why:{pt:"Wi-Fi aberto permite interceptação. Só acesse sistemas corporativos com VPN homologada.",en:"Open Wi-Fi allows interception. Only access corporate systems with approved VPN."}},
     {theme:"device",diff:2,personal:{pt:"Achar pendrive na recepção? Não plugue para 'ver o dono' — o risco é o mesmo de na operação.",en:"Found a USB in the lobby? Don't plug it in to 'find the owner' — same risk as at work."},q:{pt:"Na sala de embarque, alguém oferece carregador USB 'turbo' para seu notebook. Você:",en:"At the boarding lounge, someone offers a 'turbo' USB charger for your laptop. You:"},
      opts:[{pt:"Aceito, a bateria está acabando",en:"Accept it, the battery is dying"},{pt:"Recuso; carregadores desconhecidos podem conter juice jacking — uso carregador próprio",en:"Decline; unknown chargers may contain juice jacking — use my own charger"},{pt:"Aceito mas desligo o notebook",en:"Accept but turn off the laptop"},{pt:"Compartilho a VPN com um colega que esqueceu a senha",en:"Share the VPN with a colleague who forgot the password"}],correct:1,
      why:{pt:"Juice jacking via USB público pode comprometer o dispositivo. Use apenas carregadores confiáveis.",en:"Juice jacking via public USB can compromise the device. Use only trusted chargers."}}
    ]},
   {id:"soc", ico:"🛡️", name:{pt:"6. SOC & resposta",en:"6. SOC & response"},
    desc:{pt:"O SOC detecta login anômalo na sua conta a partir de IP estrangeiro — a história precisa de um desfecho coordenado.",en:"The SOC detects an anomalous login on your account from a foreign IP — the story needs a coordinated ending."},
    qs:[
     {theme:"password",diff:2,personal:{pt:"Código de verificação sem você ter pedido login? Trate como alerta, não como incômodo.",en:"Verification code when you didn't try to log in? Treat it as a warning, not a nuisance."},q:{pt:"O SOC pede para você trocar a senha e revisar dispositivos conectados. Você:",en:"The SOC asks you to change your password and review connected devices. You:"},
      opts:[{pt:"Ignoro, deve ser falso positivo",en:"Ignore it, must be a false positive"},{pt:"Sigo imediatamente: troco senha, ativo MFA e reviso sessões ativas",en:"Follow immediately: change password, enable MFA and review active sessions"},{pt:"Só troco a senha e sigo trabalhando",en:"Only change password and keep working"},{pt:"Uso o mesmo tablet para apps pessoais e operacionais",en:"Use the same tablet for personal and operational apps"}],correct:1,
      why:{pt:"Alertas do SOC exigem ação rápida. Troque credenciais, revise sessões e confirme MFA.",en:"SOC alerts require fast action. Change credentials, review sessions and confirm MFA."}},
     {theme:"phishing",diff:2,personal:{pt:"Pressa + link desconhecido? Pause antes de clicar — o padrão se repete fora do trabalho.",en:"Urgency + unknown link? Pause before clicking — the pattern repeats outside work."},q:{pt:"Como fechar o ciclo e proteger os escritórios Orbita a longo prazo?",en:"How to close the cycle and protect Orbita offices long term?"},
      opts:[{pt:"Programa integrado: reporte de phishing, MFA, DLP, treinamento e simulações trimestrais",en:"Integrated program: phishing reporting, MFA, DLP, training and quarterly simulations"},{pt:"Apenas bloquear sites de redes sociais",en:"Just block social media sites"},{pt:"Proibir trabalho remoto para todos",en:"Ban remote work for everyone"},{pt:"Anoto a nova senha em um arquivo de texto no desktop",en:"Write the new password in a text file on the desktop"}],correct:0,
      why:{pt:"Escritórios seguros combinam pessoas, processos e tecnologia — não uma medida isolada.",en:"Secure offices combine people, processes and technology — not a single measure."}}
    ]}
  ]}
];
